# Generated by Django 3.2.4 on 2021-07-13 02:10

import auctions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_listing_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='amount',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='bid',
            name='bidder',
            field=models.CharField(default='default', max_length=64, verbose_name=auctions.models.User),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('none', 'None'), ('electronics', 'Electronics'), ('fashion', 'Fashion'), ('toys', 'Toys'), ('home', 'Home & Garden'), ('sports', 'Sports'), ('auto', 'Automotive'), ('health', 'Health')], default='none', max_length=64),
        ),
    ]
