# Generated by Django 3.2.4 on 2021-07-14 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20210713_2323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='bidder',
            new_name='writer',
        ),
    ]
